Lager nytt Arbeid objekt for å bedre støtte utvieldse av flere typer …
navikt/k9-format pull request #76
Opened 2021-01-04 13:53 UTC by christofferlohne

…arbeidsforhold.

Flyttet infomasjon i arbeidsforhold som er bare relevant til psb, ArbeidPeriodeInfo. Denne er også uavehngig av om det er AT eller annet.
Endret på infomasjon i ArbeidPeriodeInfo som dekker nåværende informasjonsbehov.
Oppdatert tester og validator.

2021-01-18 09:52 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/PeriodeValidator.java
> +        perioder.forEach((sjekkPeriode, sjekkPerideValue) -> perioder.forEach((periode, periodeValue) -> {
Denne blir vanskeligere å lese uten innrykk (slik det var før).

2021-01-18 09:55 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/PeriodeValidator.java
> +        perioder.forEach((sjekkPeriode, sjekkPerideValue) -> perioder.forEach((periode, periodeValue) -> {
...og det blir enda lettere å lese hvis den indre løkken byttes ut med validerOverlappendePerioder under.

2021-01-18 10:13 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/PleiepengerSyktBarnValidator.java
> +            feil.add(new Feil("opptjening.FL/SN", "påkrevd", "Frilans eller SN må være satt.")); }
Flytt krøllparantes ned på linjen under.

2021-01-18 10:29 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/arbeid/ArbeidPeriodeInfo.java
> +    @JsonProperty(value = "taptArbeidTimerPerDag")
Endre til faktiskArbeidTimerPerDag

2021-01-18 10:36 UTC, stiangre commented on soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/PleiepengerBarnSøknadValidatorTest.java
> +        assert søknadsperiode.getTilOgMed() != null;
Endre til testasserts fremfor "assert".

2021-01-19 08:34 UTC, christofferlohne commented on soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/PleiepengerBarnSøknadValidatorTest.java
> +        assert søknadsperiode.getTilOgMed() != null;
fant ikke ut hva testassert er, lagt inn assertNotNull isteden.

2021-01-19 08:41 UTC, stiangre commented on soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/PleiepengerBarnSøknadValidatorTest.java
> +        assert søknadsperiode.getTilOgMed() != null;
Nettopp det jeg mente: Det er mange måter å asserte på i tester, slik som assertNotNull, assertThat osv (basert på hvilket testrammeverk man bruker).

2021-01-19 08:49 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/PleiepengerSyktBarnValidator.java
> +        if(snList.isEmpty()) { return; }
Unødvendig sjekk

2021-01-19 08:51 UTC, stiangre commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/PleiepengerSyktBarnValidator.java
> +            feil.add(new Feil(felt, "ikkeEntydigIdPåArbeidsgiver", "Ikke entydig ID på Arbeidsgiver, må oppgi enten norskIdentitetsnummer eller organisasjonsnummer."));
God tekst!

2021-01-19 08:53 UTC, stiangre commented on soknad/src/test/java/no/nav/k9/søknad/ytelse/psb/PleiepengerBarnSøknadValidatorTest.java
> +        verifyHarFeil(søknad);    }
Flytt siste krøllparantes ned på linjen under.

2021-01-19 08:54 UTC, stiangre approved these changes

2021-01-19 09:08 UTC, frode-carlsen commented
Se siste - her kommer større endringer på kontrakt

2021-01-19 14:15 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/LegacySøknad.java
> -        return barn == null ? Collections.emptyList() : Collections.unmodifiableList(barn);
må legges tilbake

2021-01-19 14:15 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/Søknad.java
> -        public static Søknad deserialize(ObjectNode node) {
må legges tilbake

2021-01-19 14:17 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Barn.java
> +    @NotNull(message = "Barn Personnummer/D-nummer må settes i søknaden.")
feilmelding? er vel ente personnummer eller fødselsdato?

2021-01-19 14:19 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/Uttak.java
> +public class Uttak {
bør angi
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.NONE, getterVisibility = JsonAutoDetect.Visibility.NONE, setterVisibility = JsonAutoDetect.Visibility.NONE, isGetterVisibility = JsonAutoDetect.Visibility.NONE, creatorVisibility = JsonAutoDetect.Visibility.NONE)

2021-01-19 14:19 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/UttakPeriodeInfo.java
> +public class UttakPeriodeInfo {
ditto

2021-01-19 14:19 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeid/Arbeid.java
> +public class Arbeid {
ditto

2021-01-19 14:20 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeid/ArbeidPeriodeInfo.java
> +public class ArbeidPeriodeInfo {
ditto

2021-01-19 14:20 UTC, frode-carlsen commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeid/Arbeidstaker.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
ditto

2021-01-19 14:21 UTC, frode-carlsen requested changes
Se ☝️

2021-01-19 14:26 UTC, frode-carlsen approved these changes

2021-01-19 14:26 UTC, frode-carlsen commented
conditionally approved

2021-01-19 15:10 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/LegacySøknad.java
> -        return barn == null ? Collections.emptyList() : Collections.unmodifiableList(barn);
ok

2021-01-19 15:11 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/LegacySøknad.java
> -        return barn == null ? Collections.emptyList() : Collections.unmodifiableList(barn);
ok

2021-01-19 15:13 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/Søknad.java
> -        public static Søknad deserialize(ObjectNode node) {
Lagt inn det som var på master

2021-01-19 15:16 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Barn.java
> +    @NotNull(message = "Barn Personnummer/D-nummer må settes i søknaden.")
Tror personnummer er optional og fødselsdato er required. 
Jeg tenkte ikke å gjøre endring her, så tar det bort

2021-01-19 15:17 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/felles/personopplysninger/Barn.java
> +    @NotNull(message = "Barn Personnummer/D-nummer må settes i søknaden.")
en av Leagacy testene feiler med NotNull

2021-01-19 16:50 UTC, christofferlohne commented on soknad/src/main/java/no/nav/k9/søknad/ytelse/psb/v1/arbeid/Arbeidstaker.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
lagt til

2021-01-19 17:00 UTC, merged